import { useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { ReminderCard } from '@/components/reminders/ReminderCard';
import {
  useReminders,
  useDismissReminder,
  useDismissAllReminders,
  useTelegramLink,
  useUnlinkTelegram,
} from '@/hooks/useReminders';
import type { ReminderType } from '@/types';

const TABS: { label: string; value: ReminderType | 'ALL' }[] = [
  { label: 'All', value: 'ALL' },
  { label: 'Birthdays', value: 'BIRTHDAY' },
  { label: 'Follow-ups', value: 'FOLLOW_UP' },
  { label: 'Briefings', value: 'MORNING_BRIEFING' },
  { label: 'Reviews', value: 'EVENING_REVIEW' },
];

export function RemindersPage() {
  const [activeTab, setActiveTab] = useState<ReminderType | 'ALL'>('ALL');

  const params: Record<string, string> = { limit: '50' };
  if (activeTab !== 'ALL') params.type = activeTab;

  const { data: reminders, isLoading } = useReminders(params);
  const dismiss = useDismissReminder();
  const dismissAll = useDismissAllReminders();
  const { data: telegramStatus } = useTelegramLink();
  const unlinkTelegram = useUnlinkTelegram();

  if (isLoading) return <LoadingSpinner />;

  const active = reminders?.filter(
    (r) => !(r.metadata as Record<string, unknown> | null)?.dismissedAt
  ) ?? [];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-semibold text-gray-800">Reminders</h2>
        {active.length > 0 && (
          <Button
            variant="secondary"
            className="text-xs"
            onClick={() => dismissAll.mutate()}
            disabled={dismissAll.isPending}
          >
            Dismiss All ({active.length})
          </Button>
        )}
      </div>

      {/* Filter tabs */}
      <div className="flex gap-2 flex-wrap">
        {TABS.map((tab) => (
          <button
            key={tab.value}
            onClick={() => setActiveTab(tab.value)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors cursor-pointer ${
              activeTab === tab.value
                ? 'bg-primary-500 text-white'
                : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Telegram linking */}
      <Card>
        <h3 className="text-sm font-semibold text-gray-700 mb-2">Telegram Notifications</h3>
        {telegramStatus?.linked ? (
          <div className="flex items-center justify-between">
            <div>
              <Badge className="bg-green-100 text-green-700">Linked</Badge>
              <span className="text-xs text-gray-500 ml-2">
                Chat ID: {telegramStatus.chatId}
              </span>
            </div>
            <Button
              variant="ghost"
              className="text-xs text-red-500"
              onClick={() => unlinkTelegram.mutate()}
              disabled={unlinkTelegram.isPending}
            >
              Unlink
            </Button>
          </div>
        ) : (
          <div>
            <p className="text-xs text-gray-500 mb-2">
              Link your Telegram account to receive reminder notifications.
            </p>
            {telegramStatus?.code ? (
              <div className="flex items-center gap-3">
                <span className="text-sm text-gray-600">
                  Send this to the bot:{' '}
                  <code className="bg-gray-100 px-2 py-1 rounded font-mono text-primary-600">
                    /start {telegramStatus.code}
                  </code>
                </span>
              </div>
            ) : (
              <span className="text-xs text-gray-400">Loading link code...</span>
            )}
          </div>
        )}
      </Card>

      {/* Reminders list */}
      {reminders && reminders.length > 0 ? (
        <div className="space-y-2">
          {reminders.map((r) => (
            <ReminderCard
              key={r.id}
              reminder={r}
              onDismiss={(id) => dismiss.mutate(id)}
              dismissing={dismiss.isPending}
            />
          ))}
        </div>
      ) : (
        <Card>
          <p className="text-sm text-gray-500 text-center py-4">
            No reminders yet. They'll appear here when generated by the cron jobs.
          </p>
        </Card>
      )}
    </div>
  );
}
